# Generated by Django 3.1.2 on 2020-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historial',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
