# Generated by Django 3.1.2 on 2020-11-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('precio', models.FloatField(null=True)),
                ('categoría', models.CharField(choices=[('Lente', 'Lente'), ('Otro', 'Otro')], max_length=200, null=True)),
                ('descripción', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creación', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.ManyToManyField(to='pedidos.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creación', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pedido', 'Pedido'), ('Enviar a taller', 'Enviar a taller'), ('Finalizado', 'Finalizado')], max_length=200, null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.producto')),
            ],
        ),
    ]
