# Generated by Django 3.1.2 on 2020-11-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='armazón',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='distancia',
            field=models.CharField(choices=[('Lejos', 'Lejos'), ('Cerca', 'Cerca')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='lado',
            field=models.CharField(choices=[('Izquierdo', 'Izquierdo'), ('Derecho', 'Derecho'), ('Ambos', 'Ambos')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoría',
            field=models.CharField(choices=[('Lente', 'Lente'), ('Otro', 'Otro')], default='Otro', max_length=200, null=True),
        ),
    ]
