# Generated by Django 3.1.2 on 2020-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20201122_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='armazón',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='distancia',
            field=models.CharField(blank=True, choices=[('Lejos', 'Lejos'), ('Cerca', 'Cerca')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lado',
            field=models.CharField(blank=True, choices=[('Izquierdo', 'Izquierdo'), ('Derecho', 'Derecho'), ('Ambos', 'Ambos')], max_length=15, null=True),
        ),
    ]
