# Generated by Django 3.1.2 on 2020-11-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('pedidos', '0004_auto_20201126_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
