# Generated by Django 3.1.2 on 2020-12-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20201202_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio_total',
        ),
    ]
