# Generated by Django 3.1.2 on 2020-11-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('especialidad', models.CharField(max_length=200, null=True)),
                ('fecha_creación', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_turno', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Cumplido', 'Cumplido'), ('No cumplido', 'No cumplido')], max_length=20, null=True)),
                ('médico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
            ],
        ),
    ]
