# Generated by Django 3.1.2 on 2020-12-02 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='turno',
        ),
        migrations.AddField(
            model_name='turno',
            name='turno_dia',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='turno_hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
